# Generated by Django 3.0.8 on 2020-10-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='cheff', max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('senha_rep', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('fechar_comanda', 'fechar a comanda'), ('ver_feed', 'visualizar o feed')],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='cliente', max_length=50)),
                ('n_mesa', models.IntegerField(default=0, unique=True)),
                ('valor', models.FloatField(blank=True, default=0.0, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cozinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='cheff', max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('senha_rep', models.CharField(max_length=50)),
            ],
            options={
                'permissions': [('pedido_pronto', 'pedido pronto'), ('ver_feed', 'visualizar o feed')],
            },
        ),
        migrations.CreateModel(
            name='Garçom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('fazer_pedido', 'incluir pedido'), ('pedido_entregue', 'pedido foi entregue'), ('ver_feed', 'visualizar o feed'), ('abrir_comanda', 'abrir uma nova comanda')],
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('fazer_pedido', 'incluir pedido'), ('ver_feed', 'visualizar o feed'), ('iniciar_movimento', 'iniciar o movimento'), ('fechar_comanda', 'fechar a comanda'), ('abrir_comanda', 'abrir uma nova comanda'), ('controlar_produtos', 'controlar produtos disponiveis')],
            },
        ),
        migrations.CreateModel(
            name='logform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='movi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento', models.CharField(choices=[('L', 'Ligado'), ('D', 'Desligado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produtocad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=255)),
                ('preco', models.FloatField(default=0.0)),
                ('tipo', models.CharField(choices=[('A', 'Alimento'), ('B', 'Bebida')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('observacao', models.TextField(blank=True, default='Sem Observações.', max_length=170)),
                ('status', models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('S', 'Saiu para entrega'), ('E', 'Foi entregue'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('comandaref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidoComanda', to='gerenciador.Comanda')),
                ('produtosPed', models.ManyToManyField(related_name='produto', to='gerenciador.Produtocad')),
            ],
        ),
    ]
