# Generated by Django 3.0.8 on 2021-01-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_auto_20210110_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pago',
            field=models.CharField(choices=[('P', 'Pago'), ('R', 'Resto'), ('N', 'Não pago')], default='N', max_length=1),
        ),
    ]
