# Generated by Django 3.0.8 on 2021-01-24 15:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0012_pagamentos_pedidored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Imagem_produto'),
        ),
    ]
