# Generated by Django 3.0.8 on 2021-02-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0015_auto_20210224_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtocad',
            old_name='Insumos',
            new_name='insumos',
        ),
        migrations.AddField(
            model_name='produtocad',
            name='quantidade',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
