# Generated by Django 3.0.8 on 2021-05-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0024_newcli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcli',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='newcli',
            old_name='first_name',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='newcli',
            old_name='password',
            new_name='Senha',
        ),
        migrations.RenameField(
            model_name='newcli',
            old_name='last_name',
            new_name='Sobrenome',
        ),
        migrations.RemoveField(
            model_name='newcli',
            name='username',
        ),
        migrations.AlterField(
            model_name='loja',
            name='porte',
            field=models.CharField(blank=True, choices=[('G', 'Gold'), ('P', 'Plat')], default='G', max_length=1),
        ),
    ]
