# Generated by Django 3.0.8 on 2021-05-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0027_auto_20210510_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='movimento',
            field=models.CharField(choices=[('L', 'Ligado'), ('D', 'Desligado')], default='D', max_length=1),
        ),
        migrations.DeleteModel(
            name='movi',
        ),
    ]
