# Generated by Django 3.0.8 on 2021-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0031_auto_20210605_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='tipo',
            field=models.CharField(choices=[('A', 'Alimento'), ('B', 'Bebida'), ('O', 'Outro')], max_length=1),
        ),
    ]
