# Generated by Django 3.0.8 on 2021-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0032_auto_20210605_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, default='Sem Observações.', max_length=50),
        ),
    ]
