# Generated by Django 3.2.12 on 2022-04-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0033_auto_20210615_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(unique=True),
        ),
    ]
