# Generated by Django 3.0.8 on 2020-10-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
