# Generated by Django 3.0.5 on 2020-05-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Produtocad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=50)),
                ('descricao', models.TextField(max_length=255)),
                ('preco', models.FloatField(max_length=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gerente',
            options={'permissions': [('fazer_pedido', 'incluir pedido'), ('ver_feed', 'visualizar o feed'), ('iniciar_movimento', 'iniciar o movimento'), ('fechar_comanda', 'fechar a comanda'), ('abrir_comanda', 'abrir uma nova comanda'), ('controlar_produtos', 'controlar produtos disponiveis')]},
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='senha_rep',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comanda',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preco',
        ),
        migrations.AddField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(default=21, verbose_name=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comanda',
            name='nome',
            field=models.CharField(default='pikadobagui', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='comandaref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidoComanda', to='gerenciador.Comanda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('E', 'Saiu para entrega')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cozinha',
            name='nome',
            field=models.CharField(default='cheff', max_length=50),
        ),
        migrations.AlterField(
            model_name='cozinha',
            name='senha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cozinha',
            name='senha_rep',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtosPedido',
            field=models.ManyToManyField(to='gerenciador.Produtocad'),
        ),
    ]
