# Generated by Django 3.0.5 on 2020-05-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerente',
            options={'permissions': [('fazer_pedido', 'incluir pedido'), ('ver_feed', 'visualizar o feed'), ('iniciar_movimento', 'iniciar o movimento'), ('fechar_comanda', 'fechar a comanda'), ('abrir_comanda', 'abrir uma nova comanda'), ('controlar_produtos', 'controlar produtos disponiveis')]},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preco',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(default=0, max_length=6),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField(max_length=6)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Comanda')),
            ],
        ),
    ]
