# Generated by Django 3.0.5 on 2020-05-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20200504_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='gerenciador.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('E', 'Saiu para entrega')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='pedidos',
            field=models.TextField(max_length=200),
        ),
    ]
