# Generated by Django 3.0.8 on 2020-10-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20201011_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='valor',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
