# Generated by Django 3.0.5 on 2020-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20200510_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocad',
            name='tipo',
            field=models.CharField(choices=[('A', 'Alimento'), ('B', 'Bebida')], default='Alimento', max_length=1),
        ),
    ]
