# Generated by Django 3.0.5 on 2020-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_auto_20200504_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='garçom',
            name='nome',
            field=models.CharField(default='garçom', max_length=255),
        ),
        migrations.AddField(
            model_name='garçom',
            name='senha',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garçom',
            name='senha_rep',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
    ]
