# Generated by Django 3.0.5 on 2020-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_produtocad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
