# Generated by Django 3.0.8 on 2020-10-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_auto_20201011_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garçom',
            new_name='Garcom',
        ),
    ]
