# Generated by Django 3.0.6 on 2020-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
