# Generated by Django 3.0.5 on 2020-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_auto_20200504_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='logform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Produtocad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='cozinha',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cozinha',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='cozinha',
            name='senha_rep',
        ),
        migrations.RemoveField(
            model_name='garçom',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='garçom',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='garçom',
            name='senha_rep',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='senha_rep',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comanda',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
