# Generated by Django 3.0.5 on 2020-05-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_auto_20200510_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtosPedido',
        ),
        migrations.AddField(
            model_name='produtocad',
            name='pedidoProdutos',
            field=models.ManyToManyField(to='gerenciador.Pedido'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(default=0),
        ),
    ]
