# Generated by Django 3.0.6 on 2020-05-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_auto_20200527_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
