# Generated by Django 3.0.5 on 2020-05-09 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_auto_20200505_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='nome',
            field=models.TextField(default='sôzé', max_length=50),
        ),
        migrations.AddField(
            model_name='comanda',
            name='pedidos',
            field=models.TextField(default='pedido cancelado', max_length=255),
        ),
        migrations.AddField(
            model_name='comanda',
            name='total',
            field=models.FloatField(default=1.0, max_length=6),
        ),
        migrations.AddField(
            model_name='cozinha',
            name='nome',
            field=models.CharField(default='cheff', max_length=50),
        ),
        migrations.AddField(
            model_name='cozinha',
            name='senha',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cozinha',
            name='senha_rep',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='comanda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Comanda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='item',
            field=models.TextField(default='salgado', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('E', 'Saiu para entrega')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='produtocad',
            name='descricao',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtocad',
            name='nome',
            field=models.TextField(default='prod', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtocad',
            name='preco',
            field=models.FloatField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
