# Generated by Django 3.0.8 on 2021-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_comanda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocad',
            name='img_prod',
            field=models.ImageField(blank=True, null=True, upload_to='img/produtos'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='valor',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
