# Generated by Django 3.0.6 on 2020-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_auto_20200528_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nome',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='nome',
            field=models.CharField(default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('s', 'Saiu para entrega'), ('E', 'Foi entregue')], default='P', max_length=1),
        ),
    ]
