# Generated by Django 3.0.5 on 2020-05-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_auto_20200508_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtosPedido',
            field=models.ManyToManyField(to='gerenciador.Produtocad'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
