# Generated by Django 3.0.6 on 2020-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_auto_20200508_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='pedidos',
            field=models.TextField(default='', max_length=255),
        ),
    ]
