# Generated by Django 3.0.8 on 2021-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_pedido_status_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocad',
            name='img_prod',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='n_mesa',
            field=models.IntegerField(),
        ),
    ]
