# Generated by Django 3.0.6 on 2020-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_auto_20200529_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='movimento',
            field=models.CharField(choices=[('L', 'Ligado'), ('D', 'Desligado')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
