# Generated by Django 3.0.6 on 2020-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0009_auto_20200522_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='nome',
            field=models.TextField(max_length=30),
        ),
    ]
