# Generated by Django 3.0.8 on 2020-07-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0009_gerente_movimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='movi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviment', models.CharField(choices=[('L', 'Ligado'), ('D', 'Desligado')], max_length=1)),
            ],
        ),
    ]
