# Generated by Django 3.0.8 on 2021-01-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0009_auto_20210113_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
