# Generated by Django 3.0.8 on 2020-08-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0010_movi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movi',
            old_name='moviment',
            new_name='movimento',
        ),
    ]
