# Generated by Django 3.0.8 on 2021-01-24 15:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0010_pedido_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('F', 'fechou comanda'), ('P', 'pagou produto'), ('R', 'Restante')], default='R', max_length=1)),
                ('valor', models.FloatField(blank=True, default=0.0)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='produtocad',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='nomeimg'),
        ),
    ]
