# Generated by Django 3.0.6 on 2020-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0010_auto_20200522_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
