# Generated by Django 3.0.8 on 2021-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0011_auto_20210124_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='pedidored',
            field=models.ManyToManyField(blank=True, related_name='pedidored', to='gerenciador.Pedido'),
        ),
    ]
