# Generated by Django 3.0.8 on 2020-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0012_remove_gerente_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, default='Sem Observações.', max_length=170),
        ),
    ]
