# Generated by Django 3.0.8 on 2021-01-24 18:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0013_auto_20210124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produtosPed',
            field=models.ManyToManyField(related_name='produto', to='gerenciador.Produtocad'),
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
