# Generated by Django 3.0.8 on 2020-09-25 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0013_auto_20200912_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Gerente'),
        ),
        migrations.AddField(
            model_name='movi',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Gerente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Gerente'),
        ),
        migrations.AddField(
            model_name='produtocad',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Gerente'),
        ),
    ]
