# Generated by Django 3.0.8 on 2020-09-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0014_auto_20200924_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movi',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='produtocad',
            name='cliente',
        ),
    ]
