# Generated by Django 3.0.8 on 2020-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0016_auto_20200926_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=6),
        ),
    ]
