# Generated by Django 3.0.8 on 2021-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0016_auto_20210224_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocad',
            name='insumos',
        ),
        migrations.AddField(
            model_name='produtocad',
            name='medida',
            field=models.CharField(choices=[('U', 'Unidade'), ('K', 'Kilo'), ('G', 'Grama'), ('L', 'Litro')], default='U', max_length=1),
        ),
    ]
