# Generated by Django 3.0.8 on 2020-09-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0017_auto_20200927_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedido realizado'), ('F', 'Fazendo'), ('S', 'Saiu para entrega'), ('E', 'Foi entregue'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
    ]
