# Generated by Django 3.0.8 on 2021-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0018_auto_20210307_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocad',
            name='qnt_minima',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='medida',
            field=models.CharField(choices=[('U', 'Unidade'), ('K', 'Kilo'), ('G', 'Grama'), ('L', 'Litro'), ('M', 'Metro')], default='U', max_length=1),
        ),
    ]
