# Generated by Django 3.0.8 on 2021-03-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0019_auto_20210311_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocad',
            name='insumos',
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='cardapio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
