# Generated by Django 3.0.8 on 2021-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0020_auto_20210311_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='cardapio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
