# Generated by Django 3.0.8 on 2021-03-14 02:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0021_auto_20210313_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocad',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtocad',
            name='img_prod',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
