# Generated by Django 3.0.8 on 2021-05-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0022_auto_20210313_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_loja', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('porte', models.CharField(blank=True, choices=[('G', 'Gold'), ('P', 'Plat')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='gerente',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_loja', to='gerenciador.Loja'),
        ),
    ]
