# Generated by Django 3.0.8 on 2021-05-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0026_auto_20210510_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.DeleteModel(
            name='Cozinha',
        ),
        migrations.DeleteModel(
            name='Garcom',
        ),
        migrations.AddField(
            model_name='comanda',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='gerente',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ger_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ins_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='movi',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pag_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ped_loja', to='gerenciador.Loja'),
        ),
        migrations.AddField(
            model_name='produtocad',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_loja', to='gerenciador.Loja'),
        ),
        migrations.AlterField(
            model_name='newcli',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_loja', to='gerenciador.Loja'),
        ),
    ]
