# Generated by Django 3.0.8 on 2021-05-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0029_auto_20210513_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerente',
            options={'permissions': [('fazer_pedido', 'incluir pedido'), ('ver_feed', 'visualizar o feed'), ('iniciar_movimento', 'iniciar o movimento'), ('fechar_comanda', 'fechar a comanda'), ('abrir_comanda', 'abrir uma nova comanda'), ('controlar_produtos', 'controlar produtos disponiveis'), ('sou_cliente', 'acesso de cliente')]},
        ),
    ]
